### ISSUE TITLE
Add http://osmlab.github.io/onosm.org/ to the main page

### ISSUE THREAD

**Issue by ngosang** [osmlab/onosm.org#10]
Add http://osmlab.github.io/onosm.org/ to the main page.

**Comment by iandees** [comment]
To which main page?

**Comment by ngosang** [comment]
https://github.com/osmlab/onosm.org

**Comment by alexandre-mbm** [comment]
:+1: 

At the GitHub's header.

**Comment by iandees** [comment]
Isn't just going to `onosm.org` the more obvious link?

**Comment by iandees** [comment]
Added a link the README that points to onosm.org. :+1:
