### ISSUE TITLE
Resolve Consistency with Tags

### ISSUE THREAD

**Issue by CurlingMan13** [osmlab/onosm.org#115]
There is an issue with being able to copy/paste the ONOSM.org generated notes into the ID editor.  I really love the update, but there are some things that fall short.

For example:
- The phone number tag gets populated with "Telephone=" but OSM uses "Phone="
- The name tag shows up as "Name: ABC Business" but OSM requires "Name=ABC Business"
- "Wheelchair Accessibility:" should be "wheelchair="
- "Website: " should be "Website="
- "Accepted payment: Visa,Mastercard,Cash" should instead be "payments:visa=yes", "payments:mastercard=yes", etc.

I'm sure I am missing a few others, but these little oversights prevent it from being straight copy-paste into iD (after verification, of course) as intended

**Comment by watmildon** [comment]
YES! This small bit of matching to OSM tags would make these notes much faster to take care of. Looking at the note generation [here](https://github.com/osmlab/onosm.org/blob/gh-pages/js/site.js#L229) it seems some work has been done recently by @ArcaneDots which should help for some fields on new notes.

The rest that follow should be read skeptically as I'm not a JS dev at all so could/will be totally wrong.

It seems the intention is to have some portions of the notes be localized into other languages (all the i18n stuff). Presumably this is to the uploader can review the full text of the note. Some fields have already been converted to their equivalent OSM tag (addr:housenumber) so I don't really know how to evaluate if we'd be breaking some workflow considerations by doing away with the translations in the notes all together. Perhaps a happy medium is to present the fully translated note and then under it have all the mapped tag to copy and paste? What is the max size of a note?

Just some loose thoughts.


----

Right after I typed all that I found this comment on a pull request with similar intent. https://github.com/osmlab/onosm.org/pull/99#discussion_r823135474

**Comment by ArcaneDots** [comment]
It has already started the process of normalizing tag and needs to be updated with the recent merge. As @watmildon mentioned its comments include discussions about what fields need to added, validation and cleaned up (Issues #94, #46, #47 and #106) before this PR will be accepted.

**Comment by iandees** [comment]
I believe the note content is _more_ consistent with OSM tagging now. As I've mentioned elsewhere the content of the notes will/should never be exactly copy-pasteable because the point is that OSM mappers should attempt to do some verification.
