### ISSUE TITLE
Add additional info to generated OSM note

### ISSUE THREAD

**Issue by sfkeller** [osmlab/onosm.org#12]
The generated OSM Note needs to be at least attributed so that these notes can be separated and filtered from other kind of OSM notes.

**Comment by CloCkWeRX** [comment]
https://wiki.openstreetmap.org/wiki/API_v0.6#Map_Notes_API doesn't really support a structured approach, so adding in text is probably the least worst solution.

**Comment by alexandre-mbm** [comment]
Would it accept HTML comments?

**Comment by ENT8R** [comment]
> Would it accept HTML comments?

No, only text is allowed. Links and emails to other websites are processed and generated on the server...

**Comment by opk12** [comment]
Some apps leave a hashtag: `#mapsme`, `#mapy.cz`, etc, which allows for keyword-based filtering in the most popular note review sites.

**Comment by iandees** [comment]
onosm adds the text "onosm.org submitted note" to every note it creates, which can be used to search for notes. For example on [NotesReview](https://ent8r.github.io/NotesReview/?query=onosm.org%20submitted%20note) or as [an RSS feed](https://api.openstreetmap.org/api/0.6/notes/search?q=%22onosm.org%20submitted%20note%22&closed=0).
