### ISSUE TITLE
semi-Mandatory street name?

### ISSUE THREAD

**Issue by HikeAndMap** [osmlab/onosm.org#120]
First of all thank you for this wonderful website - it's really amazing.

Yet there's something missing here on your website, namely:

[No street names](https://wiki.openstreetmap.org/wiki/Addresses#Addresses_without_street_names)

After looking on your site for an address I get as a response:

>We found it! Now fill in the details about your business.

>Help us by filling the complete address (housenumber, post code) or improving the previous one.

What comes next is the problem for the Philippines for example.

It "demands" as input: _Street, Housenumber, City, Zip_

Which is great, but not everywhere you have a street name! Quite a lot of places here don't have a street name, but the addresses use the place tag.

This is valid according to the consensus.

I refer here to the wiki: [Key:addr:*](https://wiki.openstreetmap.org/wiki/Key:addr:*)

> Please do not only tag addr:housenumber=*, but also add at least addr:street=* or addr:place=* for places without streets (or map the belonging to a street with a relation using associatedStreet relation or street relation.) 

Further information can be found at:

[Key:addr:place](https://wiki.openstreetmap.org/wiki/Key:addr:place)

thank for your consideration

**Comment by ArcaneDots** [comment]
I could be wrong but I don't believe there is any requirement for a street to be entered in the search box. The address fields are currently setup with the assumption that one is defined. 

We do all of our lookups address and otherwise via Nominatim. I have feeling it prefers you include one but should function normally with one being included. It is able to return a place as part of the returned address. I would appreciate a simple tutorial as I'm not familiar with the Philippines's addressing system. Knowing more about the correct behavior will helpful while trying to figure out what's source of the problem. At worst an issue might need to filed with Nominatim in order to finally fix the problem.

**Comment by HikeAndMap** [comment]
okay, let me try..

So at the first window, the main, I enter for instance a vacation house in Baguio: 63 Police village.

it correctly finds the address, so far so good.

Then I click the big huge blue "continue" button 

Now I come at the page where it asks:

Category, Business type description

underneath it, it is asked: street, housenumber, city, zip

below is name, phone number, website, social network, opening hours, wheelchair accessiblity, payment methods, etc.

It is this part street, housenumber, city, zip which is missing the part, that's instead of street there's many places worldwide that don't have a street but a place, in this case "police village"

OSM convention says the basic/minimum for an address is housenumber and either street or place
Your form doesn't support us to enter the place

Which then implies, the street is mandatory, since that's the convention of OSM.

All it takes to comply with the OSM convention - is for the form to accept EITHER street or place

In my original post I included the links to the OSM wiki. Just read on the OSM wiki about the street or place convention and it's much better explained there.

I mean I can repeat the wiki here, but what's the point of doing so?

All I'm asking in this bug report, is to comply with the OSM convention as written in the documentation.

Note ID editor and JOSM both use this convention..

When adding an address
housenumber + street name OR place is the minimum for both ID and JOSM

**Comment by ArcaneDots** [comment]
Yes, OnOsm is current setup up to handle the use case of someone living in US/EU city. I imagine that is the largest use case or at least the most familiar to developers. As part of my plans to modernize the site, I would like to  better handle different types of addresses in a cleaner way. The first is to make sure we can handle all relevant address from Nominatim. That way we don't lose any data returned from a lookup.  The next is to displaying all the location names in a more generic way so user can verify the information. In particular, I want to have one layout that can accommodate multiple address constructions. This is going to more as about understanding how the known addressing systems map to each other as a set of equivalent regional level. Things like collapsing village, town, city into one drop-down should be relatively simple as it is difficult to live in more than one at a time (I hope so). The rest may involve learning how each country runs their mail and underling addressing systems. It should be an interesting process.

**Comment by daganzdaanda** [comment]
> Yes, OnOsm is current setup up to handle the use case of someone living in US/EU city.

That seems to be the case, but it leads to a lot of problems.
See also #103 #127 #129

**Comment by iandees** [comment]
I added support for place name when your language isn't "en-US". We'll see if it is confusing/annoying. If there's a particular language/region combination that you think should definitely have place name please let me know.
