### ISSUE TITLE
Lots of notes at the Iran label point

### ISSUE THREAD

**Issue by deevroman** [osmlab/onosm.org#121]
https://ent8r.github.io/NotesReview/?view=map&map=13%2F32.6445%2F54.5586&bbox=54.4476%2C32.5898%2C54.6697%2C32.6992&apply-bbox=true&limit=100&status=all

For some reason, many users leave notes at the point where the Iran marker is located on the map.  Now ~200 notes are open, and users continue to add them

**Comment by matkoniecz** [comment]
Now it is over 700 notes. I closed all of them, and keep auto-closing new ones.

See say https://www.openstreetmap.org/note/3869772

**Comment by iandees** [comment]
Dupe of #103
