### ISSUE TITLE
Notes are created at 41.6900000, 12.7100000 if users skip first step with a direct link

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/onosm.org#122]
I'm struggling since months with notes created at these precise coordinates: 41.6900000, 12.7100000
![image](https://user-images.githubusercontent.com/94002623/216771296-1f1d7b59-f9d2-4ad8-ae2d-2febf30d68c2.png)

I did a test ([here](https://www.openstreetmap.org/note/3845609)). A note is created at those coordinates if a user skips the first step ("_Start by telling us where your business is located._") at https://www.onosm.org/ by using a direct link to https://www.onosm.org/#details

is there a way to avoid it?

**Comment by iandees** [comment]
Closing to consolidate conversation on #103.
