### ISSUE TITLE
Location marker jumps back to place node when only partial location was given

### ISSUE THREAD

**Issue by daganzdaanda** [osmlab/onosm.org#127]
To reproduce:
1. Enter a partial location in the first field (Start by telling us where your business is located), e.g. the town or city or state or country and press "Find me"
2. The response "Found it! Move the marker until it is exactly on your business." shows up, as well as the warning about the missing house number.
3. Try to drag the marker to anywhere 
4. It will always jump back to the initial position where the `place=*` node happens to be. 

Found on Windows in a variety of browsers. 

This may very well be behind a lot of misplaced notes! (see #103 #121 #124 )

**Comment by map-per** [comment]
For the search terms "Iran" and "Teheran" the locations onosm.org shows are exactly the places where OSM notes are stackpiled.

**Comment by iandees** [comment]
I believe I solved this with 0b32e6a. There was an exception getting swallowed that caused the pin to revert back to the default location once dragged. There was also a bug that enabled the button to continue in this case.

I'm not able to reproduce the problem as described after this commit, so please give it a try and let me know.

**Comment by daganzdaanda** [comment]
Great, looks fine now!
We will see if that was the main issue that led to the hundreds of notes stacked on city place nodes.
