### ISSUE TITLE
If no housenumber is entered or found, the area for moving the pin is too small

### ISSUE THREAD

**Issue by daganzdaanda** [osmlab/onosm.org#129]
Example: 

- For the first geolocation, enter "Camino Chueco, Santa Fe" or even with any housenumber like "26, Camino Chueco, Santa Fe"
- The street will be found, the pin will be set on some part of it
- The circle to move the pin is much to small to reach all of the street

This may also lead to bad entrys and misplaced notes.

**Comment by daganzdaanda** [comment]
The functionality probably was added only recently after #89 ?
It looks like a bit of finetuning could be helpful.

In cases like the "Camino Chueco", the marker is placed around the middle of the way that Nominatim returned. But there is a second way to the east going south, so this part hasn't been included in the calculation of the mid-point. 
Would it be possible to add all the parts and return an area that encompasses the whole of the street? 
Then the user could move the pin easily to the correct place.

In cases where only a city was entered or found (maybe because the street name is missing in OSM) the area to drag the pin is quite large, but there is another problem:  #127

**Comment by iandees** [comment]
This should be resolved with the changes I made in #137. Please let me know if you're still running into problems.

**Comment by daganzdaanda** [comment]
Thanks for working on this! 

I just tried the random "Camino Chueco, Santa Fe" from the original post. 
It it cool that you can see the bounding box, was that there before?

But as you can see in the screenshot, the street of that name is not completely inside the bounding box:
![image](https://github.com/osmlab/onosm.org/assets/7693297/612ed9a3-50d7-46e5-9021-51903f1ac468)

In the data, the street is divided into two ways, and [the other one](https://www.openstreetmap.org/way/14609722) is not inside the bounding box.

**Comment by iandees** [comment]
That's a limitation of Nominatim. This is the bounding box that they give back to us. I guess we could find a bounding box for the city instead? Or suggest that the user search for the city instead of just the street?
