### ISSUE TITLE
Require providing at least some basic detail

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/onosm.org#133]
Notes like

```
onosm.org submitted note from a business:
Accepted payment methods:
takeaway=undefined 
```

are not really useful. 

They are commonly created, see https://www.openstreetmap.org/note/4069989 and https://www.openstreetmap.org/note/4071738 for some of recent ones.

Maybe block note creation if info was not provided?

**Comment by iandees** [comment]
I added a check for minimum required fields (name, category/category description, city) in 0b32e6aa20c95a30e1e19c035bc0b02fd6511df2. I'm going to close this for now, but feel free to make a case for more/fewer required fields.
