### ISSUE TITLE
Add HTTPS

### ISSUE THREAD

**Issue by stevevance** [osmlab/onosm.org#14]
On Apple's iOS 10 and macOS Sierra (10.12), Safari (and maybe other clients on those OSes) cannot provide the client's GPS location unless the website is using HTTPS.

**Comment by iandees** [comment]
I'm in the process of putting Cloudflare's SSL in front of onosm.org now.

**Comment by iandees** [comment]
Ok, all done!

![image](https://cloud.githubusercontent.com/assets/261584/18921702/dad1a2ca-8573-11e6-9144-8365e5944edd.png)
