### ISSUE TITLE
Make the note in a way to easily convert it into a node

### ISSUE THREAD

**Issue by ahangarha** [osmlab/onosm.org#140]
Currently, the body of the comment cannot be turned into a node easily. For example keys are translated. This means even in English, instead of having `phone` entry we get Phone Number`.

I can understand this if the intention is to generate a note which is human readable but I think anyone who wants to create the actual node, should know the exact `key:value` which means the current note body is not that useful.

**Comment by iandees** [comment]
I made some improvement to this with https://github.com/osmlab/onosm.org/issues/115, but see #64 and #78 for more discussion.

Basically: the data coming from users of onosm needs to be verified by an OSM mapper and should not be directly copy/pasted.
