### ISSUE TITLE
Enhance user interface and make it more responsive for mobiles

### ISSUE THREAD

**Issue by sfkeller** [osmlab/onosm.org#15]
This enhancement issue is about the user interface: When in details mode:

* Current OSM element should be indicated (node id; weblink/shortlink to embed to show OSM in external page with marker?).
* Category field should'nt have "Absinth" as default value but "--Choose--"
* Category field should be same length as other fields.
* Website should be more responsive to mobiles.

This issue is related to https://github.com/osmlab/onosm.org/issues/11

**Comment by CloCkWeRX** [comment]
The category stuff should be fixed in #23 hopefully, though select2 is a pain.
