### ISSUE TITLE
Why use notes not new nodes?

### ISSUE THREAD

**Issue by palitu** [osmlab/onosm.org#16]
I have often wanted to use OSM for touring around the local country side (specifically the Margaret River Region, Australia).  I use Osmand to have the offline maps, but the POIs are never good enough to find the majority of the tourist destinations that i am looking to visit.

Is there a reason why we cannot use this system to add nodes to OSM, entered as a certain user (ie onosm), and set up a review process.  This could be something like, after 11 months, send an email to the person contributing the point informing them that if they do not confirm the details are still accurate, it will delete the node.

This will embed the details into the osm, as well as provide a way of ensuring that they are still relevant but automatically removing them.

I think that the lack of information like that is the biggest thing keeping osm behind something like google maps.

Let me know what you think, and whether it is worth progressing, or even possible.

cheers,

Leigh

**Comment by alexandre-mbm** [comment]
I have not been a contributor but I think a editor would be **another software**. Maybe a fork.

**Comment by palitu** [comment]
I'm thinking of the same end-goal: an easy way to add your business to OSM, just have it as a POI, not a note.  It should essentially be the same thing, use the API to create a point with the appropriate tags instead of a note.

**Comment by alexandre-mbm** [comment]
Okay, so it should be "intelligent" enough to prevent duplicating data.

**Comment by palitu** [comment]
yeah - i realize there is quite a bit more to it than what exists.  perhaps look for a keyword match within 1km of the point.  

Maybe you are right about it ending up being an editor :(.  I wonder if it could start out as just new nodes in the correct location?

**Comment by alexandre-mbm** [comment]
It could preparing files to review by advanced editors and attach them to notes? Another interface could manage all this like tasks.

**Comment by CloCkWeRX** [comment]
Probably the simplest would be a URL in the link for JOSM users, allowing them to download a .osm file with the relevant data in it.

**Comment by idenkov** [comment]
Notes are not the way to do this, please refer to this - http://wiki.openstreetmap.org/wiki/Notes
Just stumbled upon a note created by the site, and this will just create additional "noise" on the map. I will take a look later in the week if I can help somehow with this, but this is wrong - it is either need to be fixed or stopped.

**Comment by iandees** [comment]
Hi @idenkov. I look forward to your contribution. I appreciate your opinion but disagree that using notes is the wrong way to store the result of onosm. This site has been around for several years and hasn't caused any more noise on the map than any other OSM tool.

**Comment by smartm0use** [comment]
@iandees Why you don't allow users to add a new node instead of a note?
Do you know if it is possible to create it using a similar way to that you used for creating notes?
If I add a note about my shop, it doesn appear on map. So what does note need for?

**Comment by iandees** [comment]
Adding notes through onosm leaves information for mappers to improve OSM. If you'd like to add your information directly to OSM without adding a note, feel free to create an OSM account and click the "Edit" tab on the OpenStreetMap website.

**Comment by smartm0use** [comment]
"Adding notes through onosm leaves information for mappers to improve OSM"
Do you mean that mappers could create a new node with the data contained in the note?

I have already an OSM account and I am an active user. I'm looking for a way to create a new node with the same ease you used for adding new notes. Do you know how can I do it?

**Comment by idenkov** [comment]
@iandees First of all this is not my opinion - OSM is described where and when to use notes. 
This is very passive aggressive way to deal with critic.
So you created a script/site solely for the purpose to add notes and eventually some mapper to fill them and to hand them more work to add commercial POIs?
 

> If you'd like to add your information directly to OSM without adding a note, feel free to create an OSM account and click the "Edit" 


This makes your script pointless.

@smatmouse Yep this is what he means - to add notes and leave the actual work to the mappers and hope mappers will add POIs.

**Comment by iandees** [comment]
It's not passive aggressive… as I explained several months ago I don't want to add OSM login and node support to onosm.org. If others would like to take it on as a development challenge I'm happy to provide feedback and potentially merge a pull request.

> This makes your script pointless.

Talk about passive aggressive...

You're welcome to not use this tool and encourage people to use an OSM editor directly. This tool is designed for business owners to easily add to OSM ecosystem without worrying about signing up for OSM. Adding notes through this website means that more active OSM contributors can improve OSM.
