### ISSUE TITLE
Whites at homepage

### ISSUE THREAD

**Issue by alexandre-mbm** [osmlab/onosm.org#29]
![onosm-blanks](https://cloud.githubusercontent.com/assets/957501/23086793/074eb6cc-f54e-11e6-9218-c23d049f1fe7.png)

Tested on Firefox and Chromium. Antergos.

**Comment by alexandre-mbm** [comment]
I tried [onosm.org], not [su.openstreetmap.it]. What you are doing with them?

[onosm.org]: https://onosm.org
[su.openstreetmap.it]: http://su.openstreetmap.it

**Comment by iandees** [comment]
This is the repository for https://onosm.org. I just pushed a change: can you try again? It should fall back to English because we don't support your language yet.

**Comment by alexandre-mbm** [comment]
@iandees, is onosm.org from the oficial (upstream) repository now?

**Comment by iandees** [comment]
This repository always powered https://onosm.org.

**Comment by alexandre-mbm** [comment]
Is onosm.org the upstream, right?

**Comment by iandees** [comment]
Yes, I wrote onosm.org and the repository is this one.
