### ISSUE TITLE
Broken link: "View your note"

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/onosm.org#35]
![image](https://cloud.githubusercontent.com/assets/365751/23089851/a608d7ce-f5e0-11e6-83ef-4674838f6a86.png)

I can't quite see if it ever worked in git history, nothing refers to ```linkcoords```

**Comment by CloCkWeRX** [comment]
https://github.com/osmlab/onosm.org/pull/2/commits/4b3e8214a0f72e1350c4f26d5c26bc963d6acca8 seems to have addressed a similar bug

**Comment by iandees** [comment]
It looks like this is happening because there's an unrelated error that should be fixed in https://github.com/osmlab/onosm.org/commit/41b7fe610ff2c8960fbebff6588d39bbe17ba0c2.

**Comment by iandees** [comment]
Ah, nope. The link just doesn't get populated. That sha1 above is unrelated.
