### ISSUE TITLE
Branch for i18n?

### ISSUE THREAD

**Issue by alexandre-mbm** [osmlab/onosm.org#4]
I do not know exactly what that means but I found:
- [~~fnando/i18n-js~~](/fnando/i18n-js) ‒ _for Ruby_
- [jamuhl/i18next](/jamuhl/i18next) ‒ [**i18next.com**](http://i18next.com/) ‒ _it seems be in advanced stage of development_
- [~~mozilla/node-webmaker-i18n~~](/mozilla/node-webmaker-i18n) ‒ _for Node.js_
- [recurser/jquery-i18n](/recurser/jquery-i18n) ‒ _operates as other languages programming_
- [musterknabe/translate.js](/musterknabe/translate.js) ‒ _little abstraction_
- [joehms22/interpret.js](/joehms22/interpret.js) ‒ _little documentation_

If you want to maintain a unified and growing project, you may want to internationalize, to save effort in merging of new features.

**Comment by alexandre-mbm** [comment]
@sabas, it is better unite efforts on this issue before the project grow. Do not you think the same?

**Comment by alexandre-mbm** [comment]
@sabas, @iandees, @tmcw. Who is against the i18next for our use? I intend to resolve this issue.

**Comment by tmcw** [comment]
Sure, go for it.

**Comment by alexandre-mbm** [comment]
@sabas, I will go from the Italian version and then we will can collaborate easily in a branch `i18n`.

**Comment by humitos** [comment]
I started working on a Spanish version that we will use in Latin America soon (I hope). So, for us I will amazing if there is a way to translate the this version instead of create a fork (I've already done this to start working).

Or maybe, we can work in this site as something modular (as categories works) instead of a fixed website.

**Comment by severinmenard** [comment]
I am interested to work on a translation of the UI in French. I would suggest to implement an easy translation tool like Transifex so that non developer people (like me) can contribute to translations.

**Comment by sabas** [comment]
http://i18next.com/ has this editor http://i18next-editor.herokuapp.com/

**Comment by severinmenard** [comment]
How does it work?

**Comment by sabas** [comment]
@severinmenard I try to update suosm (https://github.com/sabas/suosm) to deal with multi language strings using that script, let's see how does it work :)

**Comment by sabas** [comment]
Just committed the "multilanguage" version.
I must still translate a few files (https://github.com/sabas/suosm/tree/gh-pages/locales/it this is the italian file, in english there's only translation.json)

**Comment by iandees** [comment]
Just to reiterate: I'd love if someone would write a pull request that added i18n support to onosm.org instead of putting it on another repo.

**Comment by sabas** [comment]
@iandees actually my edits are in #2 :-)

**Comment by severinmenard** [comment]
Any update for multilanguage in onsom.org rather than forking for every language?

**Comment by sabas** [comment]
@severinmenard I didn't find time to review the onosm.org version and do a clean commit, but it's a matter of removing all the strings from index.html, replacing with a data attribute data-i18n="property.subproperty" and reference this library http://i18next.com/
See https://github.com/sabas/suosm/blob/gh-pages/index.html and live with english enabled athttp://su.openstreetmap.it/?setLng=en (normally is in italian)

**Comment by stephan75** [comment]
Is it helpful to suggest another translation solution for onosm.org?

If yes, see https://weblate.org ... which is used by the Osmand guys.

**Comment by alexandre-mbm** [comment]
I stopped completely. Question of personal priority. I am without time for this programmation. In case of you puting strings of translation in services such as Weblate or Transifex, or in files (YAML, JSON, etc.), I probably could back to collaborate. Unhappily I have not looked for the development of the code.
