### ISSUE TITLE
Categories's placeholder is partialy hidden

### ISSUE THREAD

**Issue by alexandre-mbm** [osmlab/onosm.org#41]
![onosm-lacks-placeholder](https://cloud.githubusercontent.com/assets/957501/23090440/f5d9dd3e-f57c-11e6-96c6-8296b90584b1.png)

**Comment by CloCkWeRX** [comment]
So, there's a 'search' input text field which is doing the clipping; but I couldn't figure out how to make it longer.

I ended up choosing a shorter placeholder (Please select...) to work around it

**Comment by ArcaneDots** [comment]
I have not experienced this lately. Can anyone verify if this is still an issue for them.

**Comment by iandees** [comment]
Closing this as the design has changed significantly mid last-year.
