### ISSUE TITLE
Kanban

### ISSUE THREAD

**Issue by alexandre-mbm** [osmlab/onosm.org#43]
**[Waffle.io](https://waffle.io/)** or [HuBoard](https://huboard.com/).

**Comment by alexandre-mbm** [comment]
See the entry point: [waffle.io/osmlab/onosm.org](https://waffle.io/osmlab/onosm.org). The user need permissions to change the issues. Maybe this can be managed via a organization teams or individually.

Example:
- osmbc and its [metrics](https://github.com/TheFive/osmbc#next-steps--progress)
- osmbc and its [kanban](https://waffle.io/TheFive/osmbc) (inactive today)

**Comment by iandees** [comment]
What is "osmbc"?

**Comment by alexandre-mbm** [comment]
A OpenStreetMap's sub-project. It is a platform for collaborative article translations. They makes the [WeeklyOSM](http://www.weeklyosm.eu) by using Markdown like this:

![weeklyosm-integrator](https://raw.githubusercontent.com/alexandre-mbm/weeklyosm-integrator/master/design/mockup.png)

**Comment by alexandre-mbm** [comment]
Kanban is another thing. Waffle.io and HuBoard are alternative interfaces to manage GitHub issues.

**Comment by iandees** [comment]
Please feel free to set up waffle or huboard or something if you prefer to view GitHub tickets that way, but I don't find it useful. I'm going to close this for now until we have a need for it.

**Comment by alexandre-mbm** [comment]
Okay. All well. But my kanban would be read only.
