### ISSUE TITLE
Add 'payment options'

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/onosm.org#46]
https://github.com/osmlab/onosm.org/pull/2/commits/67592dea4ccedc070a6265259420436b8920ac83 basically

**Comment by ArcaneDots** [comment]
The Sabas fork added translated payment options listed in wiki. They can selected using a drop-down. Fork was merged as  PR #105.

**Comment by ArcaneDots** [comment]
Closing issue due earlier merge.

**Comment by ArcaneDots** [comment]
This issue should be resolved.
