### ISSUE TITLE
Make onosm.org friendly for home addresses?

### ISSUE THREAD

**Issue by landonreed** [osmlab/onosm.org#5]
@tmcw I just discovered this great little tool.  I have an OpenTripPlanner project that uses Nominatim [here](http://opentrip.atlantaregion.com/otp-leaflet-client/) and I would really like to give users a way to add their address to OSM if it doesn't show up in their search.

Would you accept an extension to onosm.org with language that is friendly for home addresses?  Maybe the root of onosm.org could stay biz-focuses and a sub-directory `home` could be focused on adding home addresses?

Thoughts?

**Comment by tmcw** [comment]
Sure! This is mostly an @iandees joint so he might have more specific ideas / opinions than I do!

**Comment by iandees** [comment]
Sure, I think such a thing makes sense. Would be happy to merge a pull request or help move one along.

**Comment by landonreed** [comment]
Great!  I'll start working on the pull.
