### ISSUE TITLE
UI/UX: path to next action (step:details) does not stand out

### ISSUE THREAD

**Issue by althio** [osmlab/onosm.org#52]
The link `<a href='#details'>add more details</a>` to move from `step:Location` to `step:Details` is not obvious.
- maybe it would be better to keep the text `<p id="success" ...>` above the map (like the `<p id="couldnt-find"`... >`
- maybe the `<a href='#details'>add more details</a>` link would be better as a button (like the `<button class='col12' id='collect-data-done' data-i18n="step2.done"></button>`

![image](https://cloud.githubusercontent.com/assets/9863567/23175714/73ecb99a-f860-11e6-8a7c-0f21fdbdef11.png)

**Comment by alexandre-mbm** [comment]
An big arrow button like of step-to-step would be better. And that feedbacks messages appearing in boxes green (positive) or red (negative).

**Comment by iandees** [comment]
This is improved a whole lot with the recent redesign, so I'm going to close.
