### ISSUE TITLE
prevent empty note

### ISSUE THREAD

**Issue by Marc-marc-marc** [osmlab/onosm.org#63]
https://www.openstreetmap.org/note/1362818
no info except long/lat
name and category should be mandatory, no ?

**Comment by hashtagdeamon** [comment]
There is also the problem that the position of the note can be not set which leads to a buildup of notes on 0/0 position. The position should be mandatory as well, as notes without a proper position are usually useless.

**Comment by iandees** [comment]
Both of these would be great things to submit pull requests for! I'm happy to give pointers to where a contribution could be made to check these scenarios.

**Comment by hashtagdeamon** [comment]
I will surely not have time this month, but if you write a suggestion how/where you would add this, I might get back to this later this summer.
