### ISSUE TITLE
add to OSM directly instead of a note

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/onosm.org#65]
So open question, should this tool essentially wrap up creating an OSM user account and transparently insert the object into OSM directly? That way:

a) the feature shows up straight away
b) no need to manually set tags from the note
c) providing an email address when they register an OSM account means they get emails when people leave changeset comments

I'm starting to see these notes pop up, but honestly not sure what we can do about them as OSM editors.

**Comment by palitu** [comment]
I think i have raised this before, and i'm not a fan of notes.  What i would like is to see the item added, as a node, then have that node expire after 12 months if the owner doesn't re-confirm their details.  

When entering in the details, notes are added to the node to the point that it is from onosm, the review date, and that the node will be removed automatically if the owner doesn't re-confirm it.

1. Owner enters details as per normal
1. onosm creates the node with all appropriate details
1. onosm registers and stores the node id
1. onosm sends emails to owners, asking them to confirm/update details
1. once a day onosm deletes all nodes that have a review date of current day

That way, onosm allows us to have a nice directory of POI's, shops, etc with up to date details, and also stops it from littering the DB with bad data.

This sort of service is something i have always wanted to see for OSM, as i would prefer to go to osmand instead of google maps for finding places and times.

For me, notes is just not the right thing for this service.

cheers,

**Comment by iandees** [comment]
The point of adding notes is that it lets more experienced OSM editors intervene in the process. If onosm were to directly add nodes, I think we'd be getting folks asking why onosm adds duplicates when a place already exists.

Another reason why I am reticent to directly add nodes is because the list of categories for a business to describe itself is intentionally large – much larger than anything OSM documents. I'd rather the business owner decide how to describe the business and a mapper decide how to map it than me write code that (a) limits the number of options the business owner can select and (b) might be wrong OSM tags.

**Comment by palitu** [comment]
I'm really curious how many people actually add nodes for notes.  I understand your reticence, but i also think that you get to help set a standard, and make OSM that much more useful for a number of people, and help to bring it into another market.

One of the reasons i say about the time frame for nodes having an expiry is to help keep the map current, and to remove old POIs if a business falls over.  I think a process like this is actually a much more consistent and cleaner way of adding POIs to the map.

either way - thanks for your work!

**Comment by andrewharvey** [comment]
> The point of adding notes is that it lets more experienced OSM editors intervene in the process. If onosm were to directly add nodes, I think we'd be getting folks asking why onosm adds duplicates when a place already exists.

In onosm you could list nearby businesses which have a similar name and confirm, hopefully that would reduce any duplicates, end of the day its already happening with maps.me duplicates being added due to updates only being around monthly. It's quite easy to delete duplicates from OSM, if they do slip though.

> I'm really curious how many people actually add nodes for notes.

Speaking for myself, I see these notes pop up, I'd consider myself an experience OSM editor but I can't do anything with these notes. They come through as anonymous so I won't trust them to add under my OSM account. But I'm not going to make a trip out to specially ground survey this one POI. Even if I did trust the notes, it's too painstaking to manually copy each tag across.

> Another reason why I am reticent to directly add nodes is because the list of categories for a business to describe itself is intentionally large – much larger than anything OSM documents. I'd rather the business owner decide how to describe the business and a mapper decide how to map it than me write code that (a) limits the number of options the business owner can select and (b) might be wrong OSM tags.

can always add this into a note tag, note is designed for exactly that to add things which should be mapped but you're not sure how to tag them.

**Comment by andrewharvey** [comment]
BTW, I'm not trying to sound negative, OSM does need something like this which allows business operators to easily add and update their details in a very straightforward UI, so very much appreciate the work that's gone into building this.

I just think it will be better if it inserted the new feature/modifications directly into OSM.

**Comment by iandees** [comment]
I do like this idea. There are lots of problems to overcome though:

1. onosm is quite simple right now. Adding directly to OSM means turning this into an almost-full-fledged editor. Where would the list of presets (business type -> OSM tags) come from?
1. People trying to add their business would get sidetracked during the OSM account signup process
1. OSM geocoding isn't good enough to put the pin in the right spot all the time. What criteria would we use to decide that the point is accurate enough to add directly to OSM?

I'd be happy to see someone work on or propose some code for some of this.

**Comment by Dr-Mx** [comment]
Be aware we don't want to turn OSM into another Google Maps where businesses that do not have a publicly visitable location are just using it as a tool for direct advertising.  The use of notes allows me to survey these places before they appear on the map.

**Comment by jarek** [comment]
If an example helps: here is an onosm.org submission that we probably wouldn't want to have added as a node: a craft business with visits "by appointment only" https://www.openstreetmap.org/note/1694287. Check imagery - this is a house, in a residential area, at most with a studio in a garage. It would not be very good if it got added to OSM as a furniture store.

**Comment by mvexel** [comment]
As mentioned [on Slack](https://osmus.slack.com/archives/C1VE7JM9T/p1571411795082400), there may be a tiered process where an OnOSM submission creates a MapRoulette task, and MapRoulette users can then validate it. 

Currently MapRoulette cannot add nodes yet, only tags, but that capability will be added soon.

**Comment by marczoutendijk** [comment]
> Another reason why I am reticent to directly add nodes is because the list of categories for a business to describe itself is intentionally large – much larger than anything OSM documents. I'd rather the business owner decide how to describe the business and a mapper decide how to map it than me write code that (a) limits the number of options the business owner can select and (b) might be wrong OSM tags.

As DWG member I did a few test runs to see onosm.org in action. 
I was highly surprised that the list of categories I had to choose from is **over 1000 items** long! That's asking for troubles. Why not limit your choices to the ones that we have in the [wiki for office categories](https://wiki.openstreetmap.org/wiki/Map_Features#Office)?

One other remark:
When the data is delivered on the website of onosm.org, users see the promise:
"_An OpenStreetMap volunteer will add your data to the map soon_".
But given the number of complaints that we receive at the DWG from people who had added their data (via onosm.org), but didn't see anything on the map appear for months, you'd better reword that sentence to be more close to the truth like "maybe it will appear on the map sometime..." 

In know that mappers in some areas handle incoming notes soon, but warning users of onosm.org that it might take quiet some time for their data to appear on the map, seems a good idea.

**Comment by iandees** [comment]
Not sure what mentioning DWG was meant to imply, but I'd be happy to cut down on the size of the category list. It was meant to give some guidance for folks on what to put in that box instead of a free-form text field. It should represent itself as an autocomplete, not just a dropdown. Using the wiki to build a better list would be a good start, but would also leave out plenty of folks who don't run offices.

**Comment by marczoutendijk** [comment]
> Not sure what mentioning DWG was meant to imply, 

Nothing but the fact that DWG is seeing the results of onosm.org-users who are not satisfied with the results...

The next part is written as [user marczoutendijk](https://www.openstreetmap.org/user/marczoutendijk)

>but I'd be happy to cut down on the size of the category list. It was meant to give some guidance for folks on what to put in that box instead of a free-form text field. It should represent itself as an autocomplete, not just a dropdown. Using the wiki to build a better list would be a good start, but would also leave out plenty of folks who don't run offices.

On the site I read: 

>"_It's easy and free to add your **business** to the map!_" 

In the first place (language thing) I interpreted that as "office", but I understand that you want to include all the things that people run/do to earn money. Then I (as a developer) would add the categories that we have as [shop](https://wiki.openstreetmap.org/wiki/Map_Features#Shop) or [craft](https://wiki.openstreetmap.org/wiki/Map_Features#Craft).
For anything that is not in the lists you offer,  add the category "other" and you're done.

If you offer the options on the website:

1. Are you running a shop: (show shops)
2. Are you running and office: (show offices)
3. Are you offering a special craft: (show crafts)

and then people choose from the standard wiki lists, you have something that is manageable.
Nobody is going to choose from a list of 1000+ items.  
I would not let people come up with their own description of their "business". It should fit in the wiki choices, which makes it also easier for the mappers who are going to handle the notes to find the right choices. 
I know, osm is "any key you like" but that is plain bullshit and one of the reasons that we have 40.000 keys in OSM that don't make sense at all. 
Feel free to read my [diary on OSM chaos](https://www.openstreetmap.org/user/marczoutendijk/diary).

**Comment by harry-wg** [comment]
OSM is primarily a **map** not a business directory. Buildings should be mapped primarily according to the prominent, street-visible signage on the building, not on the so-called "occupants" who may in some cases consist of thousands of businesses operating rented single rooms or even just mailboxes and have no prominent street-visible signage,

Let's not follow google and let people pollute the map with insignificant businesses that cannot even be seen from the street. On OSM, a building that shows no street-visible signage deserves little more than its address and postcode to be mapped, and rightly so,

It's bad enough that the opening page of onosm gives the false impression "It's easy and free to add your business to the map!" when it should prefix it with the all-important "If your business has prominent street-visible signage..." but at least the present arrangement creates only map notes, which can be easily deleted if and when an editor passes the site and cannot see adequate business signage.

**Comment by iandees** [comment]
This was a great conversation, but I'm going to close it out as a "will not fix".

It's my belief that an OSM mapper should confirm that the submitted place exists with a primary source and will likely need to fix formatting errors in the text from the submitter before entering it into OSM. Adding directly to OSM with user-submitted text from an onosm form seems like it'll introduce a lot of sloppy data.

I'm very interested in proposals with specific ideas for how to incrementally get there, but as of right now I don't see it.

See also my comments in #64 and #78.
