### ISSUE TITLE
Disable the final submit button on first click

### ISSUE THREAD

**Issue by iandees** [osmlab/onosm.org#67]
In #55, it was pointed out that onosm sometimes creates "duplicate" notes: notes with the same content at the same location. Based on the IDs of the notes being so close together, my guess is that people are double-clicking or otherwise pressing the final submit button more than once. This would result in two API calls to OSM.org and create these sorts of notes.

A fix for this would be to disable the button until we get a response back. If there was an error, turn the button back on, if it was successful show a link to the note that was created.

**Comment by hashtagdeamon** [comment]
I did not manage to double click the button to create two notes. 
However, I was able to create two notes when using »back to initial screen«-link as it did not delete the coordinates and the categories or using the browser's back button. 
In the first case, I would suggest doing a complete reload with `window.location.reload(true);`.
