### ISSUE TITLE
Category - office - is missing from category drop-down

### ISSUE THREAD

**Issue by ghost** [osmlab/onosm.org#68]

**Comment by ghost** [comment]
Also, with only one category, a comma precedes the category - https://www.openstreetmap.org/note/1529803#map=15/51.5127/-0.0672

**Comment by iandees** [comment]
That's because it's called ["Offices"](https://github.com/osmlab/onosm.org/blob/gh-pages/locales/en-US/categories.json#L635).

**Comment by ghost** [comment]
Thanks, I don't know how I missed that.

**Comment by iandees** [comment]
It is kind of weird that the category has a bunch of plurals in it. A pull request to make all categories singular would be nice to see.

**Comment by ghost** [comment]
Hmm - I ended up entering it as "office:company: as per : 

https://www.openstreetmap.org/node/5912107158

Seems like openstreetmap tags are a bit arbitrary.
