### ISSUE TITLE
Add a multilanguage option

### ISSUE THREAD

**Issue by severinmenard** [osmlab/onosm.org#7]
With an easy translation tool like Transifex would be great

**Comment by alexandre-mbm** [comment]
See #4

**Comment by CloCkWeRX** [comment]
This one might be closable now

**Comment by alexandre-mbm** [comment]
Will it be automatic always?

**Comment by CloCkWeRX** [comment]
Not quite, so maybe this one can be renamed to "Make it easy to scale translation"

**Comment by CloCkWeRX** [comment]
:(

> Transifex Live is not available for organizations in Open Source plan. Please consider upgrading to use it.

**Comment by CloCkWeRX** [comment]
It also turns out that Transifex doesn't understand our format with nested objects in it :/

**Comment by alexandre-mbm** [comment]
I refer to pages at browser.

**Comment by alexandre-mbm** [comment]
But (in your topic) another option is [POEditor](https://poeditor.com).

**Comment by iandees** [comment]
The tool now has support for multiple languages. Let's open separate issues to make it easier.
