### ISSUE TITLE
Make some fields obligatory

### ISSUE THREAD

**Issue by tuukka** [osmlab/onosm.org#71]
Make some fields obligatory to prevent accidental incomplete submissions

**Comment by iandees** [comment]
Which fields are you thinking should be obligatory?

**Comment by tuukka** [comment]
Sorry, I don't remember the case exactly anymore. Looking at the UI now, probably category and name?

**Comment by iandees** [comment]
In 3bd71f58005004d0732c3db0a93980485aeee09e, I made it so that at least one category must be selected, name must be entered, and either website or phone must be entered.

**Comment by tuukka** [comment]
Thanks!
