### ISSUE TITLE
Prevention of registrations of businesses at/from home in OSM.

### ISSUE THREAD

**Issue by JillisE** [osmlab/onosm.org#75]
In The Netherlands, there's a steady flow of anonymous notes from onosm.org regarding businesses at or from home. These aren't visible from the street nor are they meant to be visited.  Thus the consensus in the Dutch OSM community is that they shouldn't be entered in our database. The notes are (generally) solved with an explanatory comment and no edits. In very rare cases, the business owner registers himself on OSM, reopens the note and explains why his business should be on OSM.

In my opinion, the user interface of onosm.org should tell people that they should only enter businesses like shops, offices and studios that admit clients. This would help the OSM editors by limiting the amount of anonymous notes that won't be processed anyway. And it would prevent disappointment at the user's side because his request isn't going to be admitted.

**Comment by JillisE** [comment]
This matter is also raised in issue #65

**Comment by iandees** [comment]
I don't know that I can _prevent_ people from adding notes. Adding a some text will probably not stop anyone from using the form, but we could remove items from the category selection list to discourage them from adding these sorts of places. Can you go through the list and propose some to remove?

**Comment by JillisE** [comment]
Adding some discouraging/warning text was what I was thinking about.

There isn't any category to remove, as all categories of businesses at home that I've come across are also valid for regular businesses that do belong in OSM. Clothing shops, IT service companies, webdesigners: if they're on a high street or in a business park, it's ok.

**Comment by JillisE** [comment]
And while we're at it: it would be nice if spam was prevented as well. We don't need juvenile 'fun' notes about backyard activities, references to porn etc. Although this probably will be a case of reverse psychology (if you warn them not to, they're into it twice as much).

**Comment by jnicho02** [comment]
You could consider a honeytrap question/category, i.e. thank them for their submission, but reject them silently if they say yes to it being a home-based business.

**Comment by DaCor1** [comment]
> These aren't visible from the street nor are they meant to be visited. 

Thats not an acceptable threshold to exclude valid businesses IMHO

You state yourself that 

> all categories of businesses at home that I've come across are also valid for regular businesses that do belong in OSM. Clothing shops, IT service companies, webdesigners: 

> if they're on a high street or in a business park, it's ok.

There are a heck of a lot of businesses that are not on high streets or in business parks. 

>In very rare cases, the business owner registers himself on OSM, reopens the note and explains why his business should be on OSM.

What justifications have you come across? Has there been a case where a business has given their explanation and still the business has not been allowed into OSM?

> In my opinion, the user interface of onosm.org should tell people that they should only enter businesses like shops, offices and studios that admit clients. This would help the OSM editors by limiting the amount of anonymous notes that won't be processed anyway. And it would prevent disappointment at the user's side because his request isn't going to be admitted.

There are a lot of businesses out there that do not admit clients. It doesn't make them less valid than one that does

**Comment by JillisE** [comment]
"What justifications have you come across? "
One computer repair home business that *sometimes* used his home as a pickup point. That's the only case I've handled, out of a few dozens notes. 

"Has there been a case where a business has given their explanation and still the business has not been allowed into OSM?"
Not to my knowledge.

"There are a lot of businesses out there that do not admit clients. It doesn't make them less valid than one that does."
You're right, I've left a bit of text out: and/or are visible from the street. That's a condition for verifiability ("map what's on the ground").

There's a recent discussion about this subject on the Dutch forum: https://forum.openstreetmap.org/viewtopic.php?id=64968. If you run it through a translator, you might get the gist of it. Google Maps is mentioned for comparison.

**Comment by DaCor1** [comment]
Thanks, I went through that discussion on the Dutch forum and based on it the only thing of note is that your statement in your first post is inaccurate. 

> Thus the consensus in the Dutch OSM community is that they shouldn't be entered in our database.

There is no consensus in that discussion at least

**Comment by iandees** [comment]
I don't think we should limit what types of businesses can ask to be part of OSM, and I can't think of a great way of limiting it via onosm, so I'm going to close this. I'm open to specific ideas, though.
