### ISSUE TITLE
Abuse by online casino

### ISSUE THREAD

**Issue by limes11** [osmlab/onosm.org#77]
Casino Vulkan Vegas-online is continuously placing nodes in various parts of Germany looking like this:

onosm.org submitted note from a business: 
name: Casino Vulkan Vegas-online 
phone: 49 2571 51600 
website: https://casino-vulkanvegas-online.com/ 
twitter: undefined 
hours: 
category: Video Game Stores 
address: Saerbecker Str. 2 Greven North Rhine-Westphalia 48268

It is an online casino with a contact number in Cyprus. Every time I raise this as spam and it gets removed, a new one pops up somewhere else with the same content but different address. A current note is 2322821 but it might not live very long.

Please prevent such a systematic abuse of the app.

**Comment by iandees** [comment]
Thanks for flagging this. This system will never be able to entirely prevent spam like this. If there's a specific change you can suggest to make it harder to abuse, I'm open to ideas.

**Comment by limes11** [comment]
Thank you for your response. 

Are there actually any spam filters already implemented?

Here is a list of websites, these casinos use:

https://vegasslots777.com/

https://slottyvegas.com/en

https://vulkan-vegas-de.com/

https://vulkanvegas-online-casino.com/

https://slottyvegas.info

https://casino-vulkanvegas-online.com/

There are actually two, vulkanvegas from Cyprus and Slottyvegas from Malta. (Of course, these might actually be the same.)

An idea would be the following: 

- Block the creation of any nodes submitted through onosm which contain at least two of the strings
"vulkan", "vegas" and "slotty".

This would block all the nonsense. Of course, they can react to this, but let's see if they do.

Best, Limes
