### ISSUE TITLE
Switch to MapComplete

### ISSUE THREAD

**Issue by pietervdvn** [osmlab/onosm.org#82]
Hey everyone,

I have made a versatile, configurable "editor" called mapcomplete, which directly adds onto OSM instead of creating a note.

It might be interesting to switch? I already have a 'shop'-theme made - but it can use a lot of polish and more presets: mapcomplete.osm.be/shops

**Comment by iandees** [comment]
It looks like these tools serve different purposes. Thanks for sharing, though.
