### ISSUE TITLE
Possible duplicates in "category"

### ISSUE THREAD

**Issue by Tomagori** [osmlab/onosm.org#83]
This is really minor and (probably) only aesthetic, but I see "African Restaurants" listed twice in the "category" list. Quite possibly there are other duplicates as well, haven't found any upon a quick search though.

**Comment by iandees** [comment]
Thanks for spotting this. I sorted and deduped the categories in d4ab106. It looks like "African Restaurants" was just about the only duplicate, but there were plenty of ordering problems.
