### ISSUE TITLE
Add Cannabis Shops to list of categories

### ISSUE THREAD

**Issue by jmelvin** [osmlab/onosm.org#86]
The Cannabis Clinics category is too narrow for the broader space.  Recreational cannabis is now legal in many states.  Add Cannabis Shops to the list of categories to cover these business types.

I can submit a PR to propose the change.  However, I have an unrelated question.  How does a Note become part of the searchable map data?  Will businesses that file a note using the new Cannabis Shops category result in a map location with shop:cannabis tags?

**Comment by iandees** [comment]
Please do file a ticket to add a new category.

onosm.org creates an [OSM Note](https://wiki.openstreetmap.org/wiki/Notes) and relies on an OSM mapper to create the actual map data. It doesn't directly manipulate OSM map data.

**Comment by jmelvin** [comment]
Thanks @iandees for your quick reply.  Should I also provide translations for "Cannabis Shops" in the respective locales?

**Comment by iandees** [comment]
Sure, that'd be great!

**Comment by jmelvin** [comment]
Resolved by commit 130c61f745b2b08fe78bac6bd0ac0c7c3edbd1d9 (origin/gh-pages, origin/HEAD)
Author: James Melvin <jmelvin@sizzlescene.com>
Date:   Wed Apr 14 23:46:42 2021 -0400

    Add new category for Cannabis Shops in all supported locales.
