### ISSUE TITLE
&nbsp visible in French strings

### ISSUE THREAD

**Issue by opk12** [osmlab/onosm.org#88]
The following strings, copied verbatim from onosm.org visited from a `fr_FR.utf8` browser, show `&nbsp`:
- Map tab:
  - `Pour démarrer, où est situé votre commerce ou entreprise&nbsp?`
  - `Trouvez votre position actuelle&nbsp!. `
- Input fields tab:
  - `La position de votre établissement est marquéeñbsp; ajoutons plus de détails.`
  - The button at the bottom: `Terminé&nbsp!`
- Third tab:
  - `Vous pouvez voir la note fraîchement générée et d'éventuelles réponses à ce lien&nbsp:`
  - `Voulez-vous ajouter une autre note pour un nouvel établissement&nbsp?`

**Comment by iandees** [comment]
Thanks! I fixed them.
