### ISSUE TITLE
Create pin by clicking on the map

### ISSUE THREAD

**Issue by opk12** [osmlab/onosm.org#89]
To create the pin on the map, one has to enter an address and ask the web page to georeference it. Unfortunately, in many urbanized areas, OSM lacks the road names or has them incorrect, so one has to zoom the map, find a named street, type, move the pin manually. (Additionally, this is even worse for someone without local knowledge - a tourist, an armchair mapper, who leaves a note for local surveyors/mappers.)

If a double-click or right-click could create the pin, it would be convenient.

**Comment by iandees** [comment]
If the address isn't found, the user can search for the city and drag the marker on the map to make progress through the system. This can be made easier, definitely.

**Comment by ArcaneDots** [comment]
The Sabas fork creates a marker on Leaflet once an approximate location is determined. Fork was merged as  PR #105. Address information is then filled in details section.

**Comment by opk12** [comment]
Great, thanks Now `Start by telling us where your business is located.` should be augmented with `or click to center the marker on the map directly.` to document the new behavior to the user.

**Comment by ArcaneDots** [comment]
I am currently busy working on fixing Issue #103. I am also planing on reducing the number of overall translations as part of changes for Issue #106. You are welcome to submit a PR to update to the specific translation files before closing this issue.

**Comment by ArcaneDots** [comment]
The users are now able to adjust the actual business location after all address searches. In case Nominatim is not able to find the exact address they are given an even larger area in which to move the marker around. The actual area depends on the original search parameters and Nominatim's degree of success.

**Comment by ArcaneDots** [comment]
This should be completed
