### ISSUE TITLE
Stronger prompt for dragging to an accurate position

### ISSUE THREAD

**Issue by harry-wood** [osmlab/onosm.org#9]
The interface invites the user to drag the marker to a more accurate position:
_"We found it! Click and drag the marker to sit on your business, then you are ready to add details"_

but maybe that should be more prominent somehow.

It could even be forced as an extra step prior to adding details, or an extra step _after_ adding details.

For example this note: http://www.openstreetmap.org/note/256056 was generated in the wrong position, in the centroid of Paul St,  presumably because the user just searched for "Paul Street, London, England" and then moved on to adding details, without knowing they could place the marker more accurately.

In fact the Note adding interface on OpenStreetMap.org is also not clear on this (not clear that you can/should drag the marker)

**Comment by iandees** [comment]
Yup, good idea. We provably should make the drag marker thing be a required step. If its close enough or on the dot exactly they can just click continue.

**Comment by palitu** [comment]
what about having the marker always in the middle of the map?  then you move the map, not the marker?
