### ISSUE TITLE
Generic, free-form description input field

### ISSUE THREAD

**Issue by opk12** [osmlab/onosm.org#90]
A dedicated, generic catch-all field would be handy for everything that does not fit in the predefined fields.

- Address, where onosm.org does not or cannot infer it correctly, because topology (POI at an intersection or multiple nearby street names) or missing road names in OSM (unfortunately happens too often, even in urbanized areas).
- Location inside a shopping mall or a large/POI-crowded building, where the business owner will not bother with the exact pin location (the phone GPS fails inside a building) and with the Simple Indoor Tagging scheme; or in complex cases, where the user would need explicit instructions anyway.
- Non-obvious information for end users or mappers, as one would typically find in `note=* description=* fixme=*`
- General business tags: fax, whatsapp, payment, operator, brand, ...
- Tags specific to the type of POI.

**Comment by iandees** [comment]
I'd rather not have such a freeform field, because people will tend to put useless or advertising information in there. We can add more specific fields for people to enter if we want to gather more information for the types of things you suggest.
