### ISSUE TITLE
Allow user selection of language

### ISSUE THREAD

**Issue by angoca** [osmlab/onosm.org#92]
It will be great to be translated into different languages to prevent forks just for languages.
A tool like Transifex, Localise or POEditor could be used. I will help to translate into Spanish.

Also, depending on the browser configuration, the web page could be shown in the user's language, or one of the list.

**Comment by angoca** [comment]
It seems this option is already used under the locales directory. However, it is not synchronized for all languages.

Also, there should be a way to change the current language, to one of the available ones.

**Comment by iandees** [comment]
Can you give an example of when you'd want to pick a different language than the one specified by your browser?

**Comment by angoca** [comment]
Sometimes, the os or the browser is installed in English where is not the primary spoken  language, like in public places. Also, for a country with several official languages,  like Switzerland which has 4, then it will be better to change the current one.

**Comment by iandees** [comment]
I would accept a pull request that lets the user select a different language for the webpage.

As usual, translations are always appreciated.
