### ISSUE TITLE
address check by user and completion

### ISSUE THREAD

**Issue by OneKN1** [osmlab/onosm.org#97]
Once chosen the address you cannot see what you have chosen or what the result is! So the commitment is probably incomplet or wrong. The result should be in textbox that can be edit to complet the address or for addition Information. The position of the marker on the map is not affected.

**Comment by ArcaneDots** [comment]
The Sabas fork creates a marker on Leaflet once an approximate location is determined. Fork was merged as  PR #105. Address information is then filled in details section.

**Comment by ArcaneDots** [comment]
This should be completed
